version: '3.8'

volumes:
  maria_db_vol:
  
networks:
  default:
    name: network_maria_db

services:

  maria_db:
    container_name: maria_db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: faz_certo_que_da_certo
    ports:
      - 3306:3306
    volumes:
      - maria_db_vol:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1